# Generated by Django 6.0.3 on 2026-03-31 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redmine_project_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_1s', models.CharField(blank=True, db_column='name_1s', max_length=255)),
                ('name_sanda', models.CharField(blank=True, max_length=255)),
                ('project_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('lead_department', models.CharField(blank=True, max_length=255)),
                ('start_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_updated_by', models.ForeignKey(blank=True, db_column='budget_updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_updated_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, db_column='project_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['name'],
            },
        ),
    ]
