# Generated by Django 6.0.3 on 2026-04-09 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, db_column='parent_project_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subprojects', to='projects.project'),
        ),
    ]
