# Generated by Django 6.0.3 on 2026-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_parent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='redmine_created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='redmine_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
