# Generated by Django 6.0.3 on 2026-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_redmine_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deleted_in_redmine',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
