# Generated by Django 6.0.3 on 2026-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_deleted_in_redmine'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
