# Generated by Django 6.0.3 on 2026-03-31 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'expense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='project_expenses', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_expenses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.project')),
                ('responsible_employee', models.ForeignKey(db_column='responsible_employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='responsible_expenses', to='employees.employee')),
            ],
            options={
                'db_table': 'project_expenses',
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['project', 'expense_date'], name='idx_exp_project_date'), models.Index(fields=['category'], name='idx_exp_category'), models.Index(fields=['responsible_employee'], name='idx_exp_resp_employee'), models.Index(fields=['created_by'], name='idx_exp_created_by')],
            },
        ),
        migrations.CreateModel(
            name='ProjectIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('income_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_incomes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='projects.project')),
                ('responsible_employee', models.ForeignKey(db_column='responsible_employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='responsible_incomes', to='employees.employee')),
            ],
            options={
                'db_table': 'project_incomes',
                'ordering': ['-income_date', '-id'],
                'indexes': [models.Index(fields=['project', 'income_date'], name='idx_inc_project_date'), models.Index(fields=['responsible_employee'], name='idx_inc_resp_employee'), models.Index(fields=['created_by'], name='idx_inc_created_by')],
            },
        ),
    ]
