# Generated by Django 6.0.3 on 2026-05-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectincome',
            name='article',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
