# Generated by Django 6.0.3 on 2026-03-31 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_source', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_code', models.CharField(max_length=100, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sync_state',
                'ordering': ['entity_code'],
            },
        ),
        migrations.CreateModel(
            name='RedmineTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redmine_time_entry_id', models.IntegerField(db_index=True, unique=True)),
                ('issue_id', models.IntegerField(db_index=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activity_id', models.IntegerField(db_index=True)),
                ('spent_on', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.PROTECT, related_name='redmine_time_entries', to='projects.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='redmine_time_entries', to='employees.employee')),
            ],
            options={
                'db_table': 'redmine_time_entries',
                'ordering': ['-spent_on', '-id'],
                'indexes': [models.Index(fields=['project', 'spent_on'], name='idx_rte_project_spent'), models.Index(fields=['user', 'spent_on'], name='idx_rte_user_spent')],
            },
        ),
    ]
