# Generated by Django 6.0.3 on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redmine_sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redminetimeentry",
            name="issue_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
