# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redmine_sync", "0002_alter_redminetimeentry_issue_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncstate",
            name="cursor_int",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
