# Generated by Django 6.0.3 on 2026-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmine_sync', '0003_syncstate_cursor_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='redminetimeentry',
            name='is_deleted_in_redmine',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='redminetimeentry',
            name='redmine_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
