# Generated by Django 6.0.3 on 2026-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmine_sync', '0004_redminetimeentry_is_deleted_in_redmine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('trigger_source', models.CharField(max_length=100)),
                ('triggered_by', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='running', max_length=50)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('log_file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('employees_created', models.PositiveIntegerField(default=0)),
                ('employees_updated', models.PositiveIntegerField(default=0)),
                ('employees_deleted', models.PositiveIntegerField(default=0)),
                ('employees_skipped', models.PositiveIntegerField(default=0)),
                ('groups_created', models.PositiveIntegerField(default=0)),
                ('groups_updated', models.PositiveIntegerField(default=0)),
                ('groups_deleted', models.PositiveIntegerField(default=0)),
                ('groups_skipped', models.PositiveIntegerField(default=0)),
                ('group_memberships_created', models.PositiveIntegerField(default=0)),
                ('group_memberships_updated', models.PositiveIntegerField(default=0)),
                ('group_memberships_deleted', models.PositiveIntegerField(default=0)),
                ('group_memberships_skipped', models.PositiveIntegerField(default=0)),
                ('projects_created', models.PositiveIntegerField(default=0)),
                ('projects_updated', models.PositiveIntegerField(default=0)),
                ('projects_deleted', models.PositiveIntegerField(default=0)),
                ('projects_skipped', models.PositiveIntegerField(default=0)),
                ('time_entries_created', models.PositiveIntegerField(default=0)),
                ('time_entries_updated', models.PositiveIntegerField(default=0)),
                ('time_entries_deleted', models.PositiveIntegerField(default=0)),
                ('time_entries_skipped', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sync_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
