# Generated by Django 6.0.3 on 2026-03-31 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redmine_id', models.IntegerField(db_index=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['last_name', 'first_name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_year', models.PositiveSmallIntegerField()),
                ('bonus_quarter', models.PositiveSmallIntegerField()),
                ('extra_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_bonuses',
                'ordering': ['-bonus_year', '-bonus_quarter', 'employee_id'],
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='idx_bonus_employee_year_month')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'bonus_year', 'bonus_quarter'), name='uniq_employee_bonus_quarter'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='chk_employee_bonus_month_1_12'), models.CheckConstraint(condition=models.Q(('bonus_quarter__gte', 1), ('bonus_quarter__lte', 4)), name='chk_employee_bonus_quarter_1_4')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='employees.employee')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='employee_compensations', to='reference.compensationtype')),
            ],
            options={
                'db_table': 'employee_compensations',
                'ordering': ['-year', '-month', 'employee_id'],
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='idx_comp_employee_year_month')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month', 'type'), name='uniq_employee_compensation_period_type'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='chk_employee_comp_month_1_12')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('extra_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_salaries',
                'ordering': ['-year', '-month', 'employee_id'],
                'indexes': [models.Index(fields=['year', 'month'], name='idx_salary_year_month')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='uniq_employee_salary_period'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='chk_employee_salary_month_1_12')],
            },
        ),
    ]
