# Generated by Django 6.0.3 on 2026-05-21 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_binding', to='employees.employee')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_binding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_user_bindings',
                'ordering': ['employee_id'],
            },
        ),
    ]
