# Generated by Django 6.0.3 on 2026-05-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedmineGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("redmine_group_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "redmine_groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeGroupMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="employees.employee",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_memberships",
                        to="employees.redminegroup",
                    ),
                ),
            ],
            options={
                "db_table": "employee_group_memberships",
                "ordering": ["group_id", "employee_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "group"),
                        name="uniq_employee_group_membership",
                    )
                ],
            },
        ),
    ]
