# Generated by Django 6.0.3 on 2026-06-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_redminegroup_employeegroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
