# Generated by Django 6.0.3 on 2026-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_dismissal_date_employee_employment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted_in_redmine',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
